# fly.toml app configuration file generated for tarefacil on 2024-06-15T22:20:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tarefacil'
primary_region = 'gig'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --no-input'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
